<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NexaConnect.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Seeds\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="ImportPackages\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
