import {it,expect} from "vitest";
import {readApproval,approvalCommand} from "./dayApproval";
const org="33333333-3333-3333-3333-333333333333",branch="11111111-1111-1111-1111-111111111111",date="2026-09-01";
const ref={manifestId:branch,generation:1,evidenceVersion:"a".repeat(64),revisionEpoch:org,sourceRevision:0};
const sealed={sealId:org,manifestId:branch,revisionEpoch:org,sourceRevision:0};
const fixture=()=>({identity:{organizationId:org,restaurantId:org,branchId:branch,businessDate:date},version:2,status:"ready_for_review",snapshot:{timeZone:"UTC",currency:"THB",fromUtc:"2026-09-01T00:00:00Z",toUtc:"2026-09-02T00:00:00Z",grossSales:100,completedRefunds:0,netSales:100,cashVariance:0,tenders:[],orderVersion:"a".repeat(64),paymentVersion:"b".repeat(64),posVersion:"c".repeat(64),unresolvedOrders:0,unresolvedPayments:0,unresolvedRefunds:0,openShifts:0,openCashSessions:0,pendingCashReviews:0,issues:[],observedAtUtc:"2026-09-03T00:00:00Z",cutoff:{order:ref,payment:ref,pos:ref,checkId:org,sourcesCurrent:true,financialGaps:0,deliveryComplete:true,evidenceProtocolVersion:2},seals:{order:sealed,payment:sealed,pos:sealed,pendingChanges:0,journalComplete:true,deliveryComplete:true}},blockers:[],validatedAtUtc:"2026-09-03T00:00:01Z",canPrepare:true,pendingCommand:null,pendingSealChanges:0});

function approved(){const f=fixture(),decision={approvalId:org,operationId:branch,identity:f.identity,approvalVersion:1,sealVersion:2,approverSubject:"manager",reasonCode:"review_complete",approvedAtUtc:"2026-09-03T00:00:02Z",sourceValidatedAtUtc:f.validatedAtUtc,validationCheckId:org,snapshot:f.snapshot};return {identity:f.identity,version:1,status:"approved",decision,history:[decision],historyTruncated:false,validatedAtUtc:f.validatedAtUtc,canApprove:true,sealVersion:2,sealSnapshot:f.snapshot,reason:"review_complete",operationDecision:decision};}
it("binds an approved decision to the ready seal and scoped financial snapshot",()=>{expect(readApproval(approved(),org,branch,date).decision?.sealVersion).toBe(2);});
it("rejects approved state without fresh proof or with replaced source seals",()=>{const f=approved();for(const value of [{...f,validatedAtUtc:null},{...f,sealVersion:3},{...f,sealSnapshot:{...f.sealSnapshot,seals:{...f.sealSnapshot.seals,order:{...sealed,sealId:branch}}}}])expect(()=>readApproval(value,org,branch,date)).toThrow();});
it("retains historical decisions when current validity is unverified or superseded",()=>{for(const status of ["unverified","superseded"]){const f=approved();expect(readApproval({...f,status,version:2,validatedAtUtc:null,sealVersion:null,sealSnapshot:null},org,branch,date).history[0]?.approvalId).toBe(org);}});
it("rejects another tenant or restaurant and invalid decision chronology",()=>{const f=approved();for(const decision of [{...f.decision,identity:{...f.identity,organizationId:branch}},{...f.decision,identity:{...f.identity,restaurantId:branch}},{...f.decision,sourceValidatedAtUtc:"2026-09-03T00:00:03Z"},{...f.decision,approvalVersion:2}])expect(()=>readApproval({...f,decision},org,branch,date)).toThrow();});
it("bounds history and rejects unproven monetary snapshots",()=>{const f=approved();expect(()=>readApproval({...f,history:Array(21).fill(f.decision)},org,branch,date)).toThrow();expect(()=>readApproval({...f,decision:{...f.decision,snapshot:{...f.sealSnapshot,netSales:99}}},org,branch,date)).toThrow();});
it("an exact older operation can return its decision alongside the latest projection",()=>{const f=approved(),latest={...f.decision,approvalId:branch,approvalVersion:3};expect(readApproval({...f,version:3,decision:latest,history:[latest,f.decision]},org,branch,date).operationDecision?.approvalId).toBe(org);});
it("requires a positive reviewed version and a bounded reason",()=>{const f={branchId:branch,businessDate:date,operationId:org,expectedApprovalVersion:0,reviewedSealVersion:2,reasonCode:"review_complete"};expect(approvalCommand.parse(f)).toEqual(f);expect(()=>approvalCommand.parse({...f,reviewedSealVersion:0})).toThrow();expect(()=>approvalCommand.parse({...f,reasonCode:"anything"})).toThrow();});
