import {expect,it} from "vitest";
import {readSettlement} from "./daySettlement";
const org="33333333-3333-3333-3333-333333333333",branch="11111111-1111-1111-1111-111111111111",operation="22222222-2222-2222-2222-222222222222",date="2026-09-01";
function fixture(){
 const identity={organizationId:org,restaurantId:org,branchId:branch,businessDate:date};
 const command={branchId:branch,businessDate:date,operationId:operation,expectedPreparationVersion:2,preparationOperationId:org,approvalId:branch,reviewedApprovalVersion:1};
 const sources=["Order","Payment","POS"].map(source=>({source,proof:{command:{settlementId:org,operationId:operation,fence:{operationId:org,approvalId:branch,sealId:org,expiresAtUtc:"2026-09-03T00:04:00Z",window:{organizationId:org,restaurantId:org,branchId:branch,fromUtc:"2026-09-01T00:00:00Z",toUtc:"2026-09-02T00:00:00Z"}}},phase:"committed",decisionId:branch,changedAtUtc:"2026-09-03T00:00:00Z",lateWorkCount:1}}));
 const receipt={decisionId:branch,eventId:operation,correlationId:operation,settledAtUtc:"2026-09-03T00:00:00Z",settlementId:org,identity,approvalId:branch,sealVersion:2,
  snapshot:{currency:"THB",grossSales:10,completedRefunds:0,netSales:10,cashVariance:0,tenders:[]},sources:sources.map(x=>({source:x.source,sealId:org,epoch:branch,revision:1}))};
 return {settlement:{id:org,identity,command,status:"finalized",decisionId:branch,receipt,sources},canFinalize:false,sourceProofCurrent:true};
}
it("reads scoped immutable receipt and source custody counts for an accountant",()=>{const value=readSettlement(fixture(),org,branch,date);expect(value.canFinalize).toBe(false);expect(value.settlement?.receipt?.snapshot.netSales).toBe(10);});
it("rejects missing terminal acknowledgements and duplicate source ownership",()=>{const f=fixture();for(const sources of [f.settlement.sources.slice(1),[f.settlement.sources[0],f.settlement.sources[0],f.settlement.sources[2]],f.settlement.sources.map(x=>({...x,proof:{...x.proof,phase:"armed",decisionId:null}}))])expect(()=>readSettlement({...f,settlement:{...f.settlement,sources}},org,branch,date)).toThrow();});
it("rejects another tenant day receipt approval and source window",()=>{const f=fixture();expect(()=>readSettlement(f,branch,branch,date)).toThrow();expect(()=>readSettlement(f,org,branch,"2026-09-02")).toThrow();expect(()=>readSettlement({...f,settlement:{...f.settlement,receipt:{...f.settlement.receipt,approvalId:org}}},org,branch,date)).toThrow();expect(()=>readSettlement({...f,settlement:{...f.settlement,sources:f.settlement.sources.map(x=>({...x,proof:{...x.proof,command:{...x.proof.command,fence:{...x.proof.command.fence,window:{...x.proof.command.fence.window,organizationId:branch}}}}}))}},org,branch,date)).toThrow();});
it("keeps committed receipt visible while delivery is pending and identifies saved counts",()=>{const f=fixture();const committing={...f,sourceProofCurrent:false,settlement:{...f.settlement,status:"committing",sources:f.settlement.sources.map(x=>({...x,proof:{...x.proof,phase:"armed",decisionId:null}}))}};expect(readSettlement(committing,org,branch,date).settlement?.status).toBe("committing");});
it("rejects a forged decision receipt missing decision and incomplete abort",()=>{const f=fixture();expect(()=>readSettlement({...f,settlement:{...f.settlement,decisionId:null}},org,branch,date)).toThrow();expect(()=>readSettlement({...f,settlement:{...f.settlement,status:"aborted",receipt:null}},org,branch,date)).toThrow();expect(()=>readSettlement({...f,settlement:{...f.settlement,receipt:{...f.settlement.receipt,settlementId:branch}}},org,branch,date)).toThrow();});
it("loads absence without admitting a financial command",()=>{expect(readSettlement({settlement:null,canFinalize:true,sourceProofCurrent:false},org,branch,date).settlement).toBeNull();});
