import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Alert, Button, Card, Descriptions, Empty, Form, Input, List, Select, Space, Spin, Table, Tag, Typography } from "antd";
import { createApiClient } from "@nexaconnect/api-client";
import { AuthorizationUiProvider } from "@nexaconnect/authorization-ui";
import { NexaDesignProvider } from "@nexaconnect/design-system";
import { ErrorBoundary, normalizeError } from "@nexaconnect/error-handling";
import { PortalLayout } from "@nexaconnect/layout";
import { Access, PortalSection, scopedFeaturePath, sections, selectedAccess, Tenant } from "./portal";

type Session={subjectId:string;username?:string}; type AccessResponse={subjectId:string;organizations:Access[]};
type Member={organizationId:string;subjectId:string;status:string;joinedAtUtc?:string;concurrencyVersion:number};
type FeatureResponse={items?:unknown[];message?:string};
const api=createApiClient({onUnauthorized:()=>location.assign(`/bff/customer/login?returnUrl=${encodeURIComponent(location.pathname+location.hash)}`)});

function useRequest<T>(path?:string){const[data,setData]=useState<T>();const[error,setError]=useState<string>();const reload=()=>{if(path)api.request<T>(path).then(v=>{setData(v);setError(undefined)}).catch(e=>setError(normalizeError(e).message))};useEffect(reload,[path]);return{data,error,reload};}
function ContextPicker({access,tenant,onChange}:{access:Access[];tenant?:Tenant;onChange:(v:Tenant)=>void}){return <Select style={{minWidth:300}} value={tenant?`${tenant.organizationId}|${tenant.applicationCode}`:undefined} placeholder="Select organization and product" options={access.map(x=>({value:`${x.organizationId}|${x.applicationCode}`,label:`${x.organizationName} · ${x.applicationCode}`}))} onChange={async value=>{const[organizationId,applicationCode]=value.split("|");onChange(await api.request<Tenant>("/bff/customer/tenant",{method:"POST",body:{organizationId,applicationCode}}))}}/>}

function MembershipsPanel(){const state=useRequest<Member[]>("/bff/customer/memberships");const[form]=Form.useForm();const[message,setMessage]=useState<string>();const save=async(values:{subjectId:string;status:string})=>{try{await api.request(`/bff/customer/memberships/${encodeURIComponent(values.subjectId)}`,{method:"PUT",body:{status:values.status}});form.resetFields();setMessage("Membership saved.");state.reload()}catch(e){setMessage(normalizeError(e).message)}};const change=async(member:Member,status:string)=>{try{await api.request(`/bff/customer/memberships/${encodeURIComponent(member.subjectId)}`,{method:"PUT",body:{status,expectedVersion:member.concurrencyVersion}});state.reload()}catch(e){setMessage(normalizeError(e).message)}};return <><Typography.Title level={2}>Customer users & memberships</Typography.Title><Alert type="info" showIcon message="Identity credentials stay in Keycloak. Add users here by their stable Keycloak subject ID."/><Card title="Add membership" style={{marginTop:16}}><Form form={form} layout="vertical" onFinish={save}><Form.Item name="subjectId" label="Keycloak subject ID" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="status" label="Status" initialValue="active"><Select options={["invited","active","suspended"].map(value=>({value}))}/></Form.Item><Button type="primary" htmlType="submit">Save membership</Button></Form></Card>{message&&<Alert style={{marginTop:16}} type={message==="Membership saved."?"success":"error"} message={message}/>}<Table style={{marginTop:16}} rowKey="subjectId" loading={!state.data&&!state.error} dataSource={state.data} columns={[{title:"Subject",dataIndex:"subjectId"},{title:"Status",dataIndex:"status",render:v=><Tag>{v}</Tag>},{title:"Joined",dataIndex:"joinedAtUtc",render:v=>v??"—"},{title:"Actions",render:(_,member)=><Space><Button onClick={()=>change(member,"active")}>Activate</Button><Button onClick={()=>change(member,"suspended")}>Suspend</Button><Button danger onClick={()=>change(member,"removed")}>Remove</Button></Space>}]} /></>}
function FeaturePanel({section}:{section:Exclude<PortalSection,"profile"|"products"|"users"|"dashboards">}){const state=useRequest<FeatureResponse>(scopedFeaturePath(section));return <><Typography.Title level={2}>{section}</Typography.Title>{state.error&&<Alert type="warning" message={state.error}/>} {!state.data?<Spin/>:<Card><Alert type="info" message={state.data.message}/><Empty/></Card>}</>}

function App(){const session=useRequest<Session>("/bff/customer/me"),accessState=useRequest<AccessResponse>("/bff/customer/access");const[tenant,setTenant]=useState<Tenant>();const[section,setSection]=useState<PortalSection>(()=>sections.includes(location.hash.slice(1) as PortalSection)?location.hash.slice(1) as PortalSection:"profile");useEffect(()=>{api.request<Tenant>("/bff/customer/tenant").then(setTenant).catch(()=>undefined)},[]);if(!session.data||!accessState.data)return session.error||accessState.error?<Alert type="error" message={session.error??accessState.error}/>:<Spin fullscreen/>;const access=accessState.data.organizations,current=selectedAccess(access,tenant);const labels:Record<PortalSection,string>={profile:"Organization profile",products:"Enabled products",users:"Customer users & memberships",configuration:"Product configuration",branches:"Branches & locations",dashboards:"Product dashboards",reports:"Reports",media:"Media management",activity:"Activity & audit history"};const nav=sections.map(key=>({key,label:labels[key],onSelect:()=>{location.hash=key;setSection(key)}}));let panel:React.ReactNode;if(!tenant||!current)panel=<Card><Typography.Title level={2}>Choose your workspace</Typography.Title><ContextPicker access={access} tenant={tenant} onChange={setTenant}/></Card>;else if(section==="profile")panel=<><Typography.Title level={2}>Organization profile</Typography.Title><Descriptions bordered><Descriptions.Item label="Organization">{current.organizationName}</Descriptions.Item><Descriptions.Item label="Code">{current.organizationCode}</Descriptions.Item><Descriptions.Item label="Organization ID">{current.organizationId}</Descriptions.Item><Descriptions.Item label="Product"><Tag>{current.applicationCode}</Tag></Descriptions.Item></Descriptions></>;else if(section==="products")panel=<><Typography.Title level={2}>Enabled products</Typography.Title><List dataSource={access.filter(x=>x.organizationId===current.organizationId)} renderItem={x=><List.Item>{x.applicationCode}</List.Item>}/></>;else if(section==="users")panel=<MembershipsPanel/>;else if(section==="dashboards")panel=<><Typography.Title level={2}>Product dashboards</Typography.Title><Alert type="info" message="Product metrics require future product-owned contracts."/></>;else panel=<FeaturePanel section={section}/>;return <AuthorizationUiProvider can={()=>true}><PortalLayout title="Customer Portal" items={nav} selectedKey={section} headerActions={<Space><ContextPicker access={access} tenant={tenant} onChange={setTenant}/><span>{session.data.username??session.data.subjectId}</span><Button href="/bff/customer/logout">Sign out</Button></Space>}>{panel}</PortalLayout></AuthorizationUiProvider>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><NexaDesignProvider><ErrorBoundary fallback={()=><Alert type="error" message="The portal could not render safely."/>}><App/></ErrorBoundary></NexaDesignProvider></React.StrictMode>);
