DROP TABLE notification_delivery_attempts;
DROP FUNCTION prevent_notification_delivery_attempt_mutation();
DROP INDEX uq_notifications_provider_message;
DROP INDEX ix_notifications_delivery_due;
ALTER TABLE notifications DROP CONSTRAINT uq_notifications_id_organization;
ALTER TABLE notifications DROP CONSTRAINT ck_notifications_delivery_schedule;
ALTER TABLE notifications DROP CONSTRAINT ck_notifications_delivery_terminal;
ALTER TABLE notifications DROP CONSTRAINT ck_notifications_delivery_lease;
ALTER TABLE notifications DROP CONSTRAINT ck_notifications_delivery_attempts;
ALTER TABLE notifications DROP CONSTRAINT ck_notifications_delivery_text;
ALTER TABLE notifications DROP CONSTRAINT ck_notifications_delivery_status;
UPDATE notifications SET status='queued' WHERE status IN('submitting','retry_scheduled');
UPDATE notifications SET status='provider_accepted' WHERE status='reconciling';
ALTER TABLE notifications DROP COLUMN concurrency_version;
ALTER TABLE notifications DROP COLUMN last_error_category;
ALTER TABLE notifications DROP COLUMN delivery_failed_at_utc;
ALTER TABLE notifications DROP COLUMN delivered_at_utc;
ALTER TABLE notifications DROP COLUMN provider_accepted_at_utc;
ALTER TABLE notifications DROP COLUMN delivery_locked_until_utc;
ALTER TABLE notifications DROP COLUMN delivery_lease_id;
ALTER TABLE notifications DROP COLUMN next_receipt_attempt_at_utc;
ALTER TABLE notifications DROP COLUMN next_delivery_attempt_at_utc;
ALTER TABLE notifications DROP COLUMN receipt_attempts;
ALTER TABLE notifications DROP COLUMN delivery_attempts;
ALTER TABLE notifications DROP COLUMN provider_message_id;
ALTER TABLE notifications DROP COLUMN provider_code;
ALTER TABLE notifications DROP COLUMN correlation_id;
ALTER TABLE notifications DROP COLUMN updated_at_utc;
