import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Alert, Button, Card, Col, Descriptions, Form, Input, InputNumber, List, Row, Select, Space, Spin, Statistic, Table, Tag, Typography } from "antd";
import { createApiClient } from "@nexaconnect/api-client";
import { AuthorizationUiProvider, Authorized } from "@nexaconnect/authorization-ui";
import { NexaDesignProvider } from "@nexaconnect/design-system";
import { PortalLayout } from "@nexaconnect/layout";
import { normalizeError, ErrorBoundary } from "@nexaconnect/error-handling";
import { capabilitiesFor, parseAdminLinks } from "./portal";

const normalizeUnknownError = normalizeError;
const NexaDesignSystemProvider = NexaDesignProvider;
function ReactErrorBoundary({ fallback, children }: { fallback: React.ReactNode; children: React.ReactNode }) {
  return <ErrorBoundary fallback={() => fallback}>{children}</ErrorBoundary>;
}

type Session = { subjectId: string; username?: string; roles?: string[] };
type Summary = { organizationCount:number; activeOrganizationCount:number; activeMembershipCount:number; registeredProductCount:number; enabledProductAccessCount:number; activeSupportElevationCount:number; asOfUtc:string };
type PlatformUser = { subjectId:string; username:string; email?:string; enabled:boolean; roles:string[] };
type PlatformRole = { code:string; description:string; permissions:string[] };
type AuditRecord = { auditId:string; action:string; resourceType:string; resourceId:string; actorSubjectId:string; outcome:string; occurredAtUtc:string };
const api=createApiClient({onUnauthorized:()=>location.assign(`/bff/platform-admin/login?returnUrl=${encodeURIComponent(location.pathname+location.hash)}`)});
const sections=["summary","organizations","memberships","products","subscriptions","users","roles","audit","support","administration"] as const;
type Section=typeof sections[number];

function useLoad<T>(path:string,enabled=true){const[data,setData]=useState<T>();const[error,setError]=useState<string>();const reload=()=>{if(enabled)api.request<T>(path).then(setData).catch(e=>setError(normalizeUnknownError(e).message));};useEffect(reload,[path,enabled]);return{data,error,reload};}
function ActionForm({title,fields,submit,method="POST"}:{title:string;fields:React.ReactNode;submit:(v:Record<string,unknown>)=>string;method?:string}){const[form]=Form.useForm();const[message,setMessage]=useState<string>();const save=async(v:Record<string,unknown>)=>{setMessage(undefined);try{await api.request(submit(v),{method,body:v});form.resetFields();setMessage("Saved successfully.");}catch(e){setMessage(normalizeUnknownError(e).message);}};return <Card title={title}><Form form={form} layout="vertical" onFinish={save}>{fields}<Button type="primary" htmlType="submit">Save</Button>{message&&<Alert style={{marginTop:16}} message={message} type={message.startsWith("Saved")?"success":"error"}/>}</Form></Card>;}

function SummaryPanel(){const state=useLoad<Summary>("/bff/platform-admin/platform/summary");const s=state.data;if(!s)return state.error?<Alert type="error" message={state.error}/>:<Spin/>;const values:[[string,number],[string,number],[string,number],[string,number],[string,number],[string,number]]=[["Organizations",s.organizationCount],["Active organizations",s.activeOrganizationCount],["Active memberships",s.activeMembershipCount],["Registered products",s.registeredProductCount],["Enabled subscriptions",s.enabledProductAccessCount],["Active support elevations",s.activeSupportElevationCount]];return <><Typography.Title level={2}>Cross-product summary</Typography.Title><Alert type="info" showIcon message="Control-plane totals only. Detailed business metrics remain product-owned."/><Row gutter={[16,16]} style={{marginTop:16}}>{values.map(([title,value])=><Col xs={24} md={8} key={title}><Card><Statistic title={title} value={value}/></Card></Col>)}</Row></>;}
function UsersPanel(){const state=useLoad<PlatformUser[]>("/bff/platform-admin/platform/users");return <><Typography.Title level={2}>Platform users</Typography.Title><ActionForm title="Create platform user" submit={()=>"/bff/platform-admin/platform/users"} fields={<><Form.Item name="username" label="Username" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="email" label="Email"><Input/></Form.Item><Form.Item name="enabled" initialValue={true} hidden><Input/></Form.Item><Form.Item name="roles" label="Roles" rules={[{required:true}]}><Select mode="multiple" options={["platform-owner","platform-admin","platform-support","platform-auditor"].map(value=>({value}))}/></Form.Item></>}/><Table style={{marginTop:16}} rowKey="subjectId" dataSource={state.data} columns={[{title:"Username",dataIndex:"username"},{title:"Email",dataIndex:"email"},{title:"Enabled",dataIndex:"enabled",render:v=>v?"Yes":"No"},{title:"Roles",dataIndex:"roles",render:(r:string[])=><Space wrap>{r.map(x=><Tag key={x}>{x}</Tag>)}</Space>}]} /></>;}
function RolesPanel(){const state=useLoad<PlatformRole[]>("/bff/platform-admin/platform/roles");return <><Typography.Title level={2}>Platform roles and permissions</Typography.Title><Alert type="info" showIcon message="Platform roles never grant customer or product operational access."/><List dataSource={state.data} renderItem={role=><List.Item><Descriptions title={role.code} column={1}><Descriptions.Item label="Purpose">{role.description}</Descriptions.Item><Descriptions.Item label="Permissions"><Space wrap>{role.permissions.map(p=><Tag key={p}>{p}</Tag>)}</Space></Descriptions.Item></Descriptions></List.Item>}/></>;}
function AuditPanel(){const state=useLoad<AuditRecord[]>("/bff/platform-admin/platform/audit?limit=100");return <><Typography.Title level={2}>Audit log</Typography.Title>{state.error&&<Alert type="error" message={state.error}/>}<Table rowKey="auditId" dataSource={state.data} columns={[{title:"Time",dataIndex:"occurredAtUtc"},{title:"Action",dataIndex:"action"},{title:"Resource",render:(_,r)=>`${r.resourceType}: ${r.resourceId}`},{title:"Actor",dataIndex:"actorSubjectId"},{title:"Outcome",dataIndex:"outcome"}]}/></>;}

function ManagementPanel({section}:{section:Section}){
if(section==="organizations")return <><Typography.Title level={2}>Organization management</Typography.Title><ActionForm title="Create organization" submit={()=>"/bff/platform-admin/organizations"} fields={<><Form.Item name="code" label="Code" rules={[{required:true,pattern:/^[a-z0-9][a-z0-9_-]{0,63}$/}]}><Input/></Form.Item><Form.Item name="name" label="Name" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="defaultTimeZone" label="IANA time zone" initialValue="UTC" rules={[{required:true}]}><Input/></Form.Item></>}/></>;
if(section==="memberships")return <><Typography.Title level={2}>Membership management</Typography.Title><ActionForm title="Set organization membership" method="PUT" submit={v=>`/bff/platform-admin/organizations/${v.organizationId}/members/${encodeURIComponent(String(v.subjectId))}`} fields={<><Form.Item name="organizationId" label="Organization ID" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="subjectId" label="Identity subject ID" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="status" label="Status" initialValue="active"><Select options={["invited","active","suspended","removed"].map(value=>({value}))}/></Form.Item></>}/></>;
if(section==="products")return <><Typography.Title level={2}>Product registry</Typography.Title><ActionForm title="Register product" submit={()=>"/bff/platform-admin/products"} fields={<><Form.Item name="applicationCode" label="Application code" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="name" label="Product name" rules={[{required:true}]}><Input/></Form.Item></>}/></>;
return <><Typography.Title level={2}>Product enablement and subscriptions</Typography.Title><Alert type="info" showIcon message="The current subscription contract records organization-level enablement; billing and plan data are not yet part of the control plane."/><ActionForm title="Change product access" method="PUT" submit={v=>`/bff/platform-admin/organizations/${v.organizationId}/products`} fields={<><Form.Item name="organizationId" label="Organization ID" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="applicationCode" label="Application code" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="status" label="Status" initialValue="enabled"><Select options={["enabled","suspended","disabled"].map(value=>({value}))}/></Form.Item></>}/></>;
}
function SupportPanel(){return <><Typography.Title level={2}>Platform support workflow</Typography.Title><Alert type="warning" showIcon message="Elevation is reasoned, time-limited, independently approved, revocable, and audited. It does not authorize product operations by itself."/><Authorized capability="support.request"><ActionForm title="Request support elevation" submit={()=>"/bff/platform-admin/support-elevations"} fields={<><Form.Item name="organizationId" label="Organization ID" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="applicationCode" label="Application code" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="reason" label="Reason" rules={[{required:true,min:10}]}><Input.TextArea/></Form.Item><Form.Item name="durationMinutes" label="Duration (minutes)" initialValue={30} rules={[{required:true,type:"number",min:5,max:240}]}><InputNumber min={5} max={240}/></Form.Item></>}/></Authorized></>;}
function AdminLinksPanel(){const links=parseAdminLinks(import.meta.env.VITE_PRODUCT_ADMIN_LINKS,location.origin);return <><Typography.Title level={2}>Product administration portals</Typography.Title><Alert type="info" showIcon message="Controlled links open separately deployed product administration boundaries; product operations are never embedded here."/><List dataSource={links} locale={{emptyText:"No product administration links are configured."}} renderItem={link=><List.Item actions={[<Button key="open" href={link.url} target="_blank" rel="noopener noreferrer">Open portal</Button>]}><List.Item.Meta title={link.label} description={link.applicationCode}/></List.Item>}/></>;}

function App(){const session=useLoad<Session>("/bff/platform-admin/me");const[section,setSection]=useState<Section>(()=>(sections.includes(location.hash.slice(1) as Section)?location.hash.slice(1):"summary") as Section);const roles=session.data?.roles??[];const capabilities=useMemo(()=>capabilitiesFor(roles),[roles.join("|")]);if(!session.data)return session.error?<Alert type="error" message={session.error}/>:<Spin fullscreen/>;const capability=(key:Section)=>key==="summary"?"summary.read":key==="organizations"?"organizations.manage":key==="memberships"?"memberships.manage":key==="products"?"products.manage":key==="subscriptions"?"subscriptions.manage":key==="users"?"users.manage":key==="roles"?"roles.read":key==="audit"?"audit.read":key==="support"?"support.request":"admin-links.open";const nav=sections.map(key=>({key,label:key[0]!.toUpperCase()+key.slice(1),capability:capability(key),onSelect:()=>{location.hash=key;setSection(key);}}));let panel:React.ReactNode=section==="summary"?<SummaryPanel/>:["organizations","memberships","products","subscriptions"].includes(section)?<ManagementPanel section={section}/>:section==="users"?<UsersPanel/>:section==="roles"?<RolesPanel/>:section==="audit"?<AuditPanel/>:section==="support"?<SupportPanel/>:<AdminLinksPanel/>;if(!capabilities.has(capability(section)))panel=<Alert type="error" message="This section is not available for your platform role."/>;return <AuthorizationUiProvider can={c=>capabilities.has(c)}><PortalLayout title="Product Owner" items={nav} selectedKey={section} headerActions={<Space><span>{session.data.username??session.data.subjectId}</span><Button href="/bff/platform-admin/logout">Sign out</Button></Space>}>{panel}</PortalLayout></AuthorizationUiProvider>;}
createRoot(document.getElementById("root")!).render(<React.StrictMode><NexaDesignSystemProvider><ReactErrorBoundary fallback={<Alert type="error" message="The portal could not render safely."/>}><App/></ReactErrorBoundary></NexaDesignSystemProvider></React.StrictMode>);
