import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {readSettings} from './settings.mjs';
import {completeEvidence} from './safe-reporter.mjs';
import {scenarios} from './scenarios.mjs';
function fixture(){const temp=mkdtempSync(join(tmpdir(),'nexa-cashier-')),runId='a'.repeat(32),dir=join(temp,'cashier-day-cutoff',runId);mkdirSync(dir,{recursive:true});const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;const from=new Date(Date.now()-86400000*2);from.setUTCHours(17,0,0,0);const to=new Date(from.getTime()+86400000);const state={runId,organizationId:id(1),otherOrganizationId:id(2),restaurantId:id(3),branchId:id(4),deniedBranchId:id(5),fromUtc:from.toISOString(),toUtc:to.toISOString(),businessDate:new Date(from.getTime()+7*3600000).toISOString().slice(0,10),cashier:{storeId:id(6),terminalId:id(7),productId:id(8)}};const path=join(dir,'fixture.json');writeFileSync(path,JSON.stringify(state));const p='NEXACONNECT_FINANCIAL_PORTAL_',settings={ENABLED:'1',CONFIRM_DISPOSABLE:'1',RUN_ID:runId,STATE_PATH:path,FIXTURE_DLL:resolve('../Tools/NexaConnect.FinancialPortalAcceptance/bin/Debug/net10.0/NexaConnect.FinancialPortalAcceptance.dll'),BASE_URL:'https://127.0.0.1:15001',OIDC_ISSUER:`http://127.0.0.1:15002/realms/nexa-review-it-${runId}`,PROXY_PORT:'15003',REPORTING_PORT:'15004',SOURCE_PROXY_PORT:'15005',PAYMENT_PORT:'15006',CALLBACK_PORT:'15007',READER_USERNAME:'cashier',READER_PASSWORD:'test',RESOLVER_USERNAME:'manager',RESOLVER_PASSWORD:'test',SECOND_MANAGER_USERNAME:'second',SECOND_MANAGER_PASSWORD:'test',DAY_CLOSE:'1',END_OF_DAY:'1',CASHIER_DAY_CUTOFF:'1',ACCOUNTANT_USERNAME:'accountant',ACCOUNTANT_PASSWORD:'test',CASHIER_DAY_CLOSE:'1',POS_URL:'http://127.0.0.1:15008/',ORDER_URL:'http://127.0.0.1:15009/',CATALOG_URL:'http://127.0.0.1:15010/',INVENTORY_URL:'http://127.0.0.1:15011/',KITCHEN_URL:'http://127.0.0.1:15012/'};return {env:Object.fromEntries(Object.entries(settings).map(([k,v])=>[p+k,v])),cleanup:()=>rmSync(temp,{recursive:true,force:true}),state,path,p};}
test('requires disposable cashier mode and the fixed fixture executable',()=>{const f=fixture();try{assert.equal(readSettings(f.env).refs.storeId,f.state.cashier.storeId);for(const key of ['CONFIRM_DISPOSABLE','CASHIER_DAY_CUTOFF','CASHIER_DAY_CLOSE','DAY_CLOSE','END_OF_DAY'])assert.throws(()=>readSettings({...f.env,[f.p+key]:'0'}));assert.throws(()=>readSettings({...f.env,[f.p+'FIXTURE_DLL']:resolve('other.dll')}));}finally{f.cleanup();}});
test('rejects remote endpoints credentials and colliding command callback ports',()=>{const f=fixture();try{for(const value of ['http://example.org/','http://user:secret@127.0.0.1:15008/','http://127.0.0.1:15008/private'])assert.throws(()=>readSettings({...f.env,[f.p+'POS_URL']:value}));assert.throws(()=>readSettings({...f.env,[f.p+'CALLBACK_PORT']:'15008'}));assert.throws(()=>readSettings({...f.env,[f.p+'SECOND_MANAGER_USERNAME']:'cashier'}));assert.throws(()=>readSettings({...f.env,[f.p+'ACCOUNTANT_USERNAME']:'manager'}));}finally{f.cleanup();}});
test('rejects source scope run mismatch malformed references and open window',()=>{const f=fixture();try{for(const patch of [{runId:'b'.repeat(32)},{cashier:{...f.state.cashier,terminalId:f.state.cashier.storeId}},{toUtc:new Date(Date.now()+60000).toISOString()},{businessDate:'invalid'}]){writeFileSync(f.path,JSON.stringify({...f.state,...patch}));assert.throws(()=>readSettings(f.env));}}finally{f.cleanup();}});
test('requires exactly twelve distinct passes without retries skips or omissions',()=>{const results=scenarios.map(title=>({title,status:'passed'}));assert.equal(completeEvidence('passed',results),true);for(const values of [results.slice(1),[...results,results[0]],results.map((v,i)=>i? v:{...v,status:'skipped'}),results.map((v,i)=>i? v:{...v,title:scenarios[1]})])assert.equal(completeEvidence('passed',values),false);assert.equal(completeEvidence('failed',results),false);});
