ALTER TABLE payment_intents DROP CONSTRAINT ck_payment_intents_status;
ALTER TABLE payment_intents ADD CONSTRAINT ck_payment_intents_status CHECK (status IN ('pending', 'authorizing', 'unknown', 'requires_action', 'authorized', 'captured', 'failed', 'cancelled', 'expired'));
ALTER TABLE payment_intents ADD COLUMN lease_owner text NULL;
ALTER TABLE payment_intents ADD COLUMN lease_expires_at_utc timestamptz NULL;
ALTER TABLE payment_intents ADD COLUMN authorization_attempt_count integer NOT NULL DEFAULT 0;
ALTER TABLE payment_intents ADD COLUMN last_reconciled_at_utc timestamptz NULL;
ALTER TABLE payment_intents ADD CONSTRAINT ck_payment_intents_lease_owner CHECK (lease_owner IS NULL OR char_length(btrim(lease_owner)) BETWEEN 1 AND 200);
ALTER TABLE payment_intents ADD CONSTRAINT ck_payment_intents_authorization_attempts CHECK (authorization_attempt_count >= 0 AND authorization_attempt_count <= 100);
ALTER TABLE payment_audit_records DROP CONSTRAINT ck_payment_audit_records_action;
ALTER TABLE payment_audit_records ADD CONSTRAINT ck_payment_audit_records_action CHECK (action IN ('payment.intent.created', 'payment.authorization.started', 'payment.authorization.succeeded', 'payment.authorization.failed', 'payment.authorization.uncertain', 'payment.authorization.reconciled'));
CREATE INDEX ix_payment_intents_expired_authorization_leases ON payment_intents (lease_expires_at_utc) WHERE status = 'authorizing' AND lease_expires_at_utc IS NOT NULL;
COMMENT ON COLUMN payment_intents.lease_owner IS 'Opaque service worker identity; never a user identity or provider secret.';
COMMENT ON COLUMN payment_intents.authorization_attempt_count IS 'Bounded number of provider authorization attempts.';
