using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using NexaConnect.Contracts.Platform;using NexaConnect.Services.Restaurant.Application.Branches;
namespace NexaConnect.Services.Restaurant.Controllers;
[ApiController,Authorize(Roles="customer-owner,customer-admin")][Route("api/restaurant/v1/customer/organizations/{organizationId:guid}/branches")]
public sealed class CustomerBranchesController(BranchManagement management,IBranchCustomerAuthorizer authorizer,ILogger<CustomerBranchesController> logger):ControllerBase
{
 [HttpGet]public async Task<IActionResult> List(Guid organizationId,CancellationToken c){if(!await Granted(organizationId,null,null,ProductPermissions.RestaurantBranchRead,c))return Forbid();return Ok(await management.ListAsync(organizationId,c));}
 [HttpPost]public async Task<IActionResult> Create(Guid organizationId,CreateManagedBranchCommand request,CancellationToken c){if(!await Granted(organizationId,request.RestaurantId,null,ProductPermissions.RestaurantBranchManage,c))return Forbid();try{var result=await management.CreateAsync(organizationId,request,Actor()!,c);return result is null?NotFound():StatusCode(201,result);}catch(ArgumentException e){return BadRequest(new ProblemDetails{Title=e.Message,Status=400});}catch(BranchConflictException e){return Conflict(new ProblemDetails{Title=e.Message,Status=409});}}
 [HttpPut("{branchId:guid}")]public async Task<IActionResult> Update(Guid organizationId,Guid branchId,UpdateManagedBranchCommand request,CancellationToken c){if(!await Granted(organizationId,null,branchId,ProductPermissions.RestaurantBranchManage,c))return Forbid();try{return Ok(await management.UpdateAsync(organizationId,branchId,request,Actor()!,c));}catch(ArgumentException e){return BadRequest(new ProblemDetails{Title=e.Message,Status=400});}catch(BranchConflictException e){return Conflict(new ProblemDetails{Title=e.Message,Status=409});}}
 private async Task<bool> Granted(Guid organizationId,Guid? restaurantId,Guid? branchId,string permission,CancellationToken c){string? actor=Actor();string authorization=Request.Headers.Authorization.ToString();bool granted=actor is not null&&await authorizer.IsGrantedAsync(organizationId,restaurantId,branchId,permission,authorization,c);if(!granted)logger.LogWarning("Customer branch authorization denied for organization {OrganizationId}, restaurant {RestaurantId}, branch {BranchId}, permission {Permission}, actor {ActorSubjectId}",organizationId,restaurantId,branchId,permission,actor);return granted;}private string? Actor()=>User.FindFirstValue("sub")??User.FindFirstValue(ClaimTypes.NameIdentifier);
}
