<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\NexaConnect.Infrastructure\NexaConnect.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\NexaConnect.Observability\NexaConnect.Observability.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\NexaConnect.Contracts\NexaConnect.Contracts.csproj" />
  </ItemGroup>
</Project>
