extern alias KITCHEN;extern alias MIGRATIONS;
using KitchenContext=KITCHEN::NexaConnect.Services.Kitchen.Application.KitchenMutationContext;using KitchenCreate=KITCHEN::NexaConnect.Services.Kitchen.Application.CreateKitchenTicket;using KitchenLine=KITCHEN::NexaConnect.Services.Kitchen.Application.KitchenTicketLine;using KitchenRepository=KITCHEN::NexaConnect.Services.Kitchen.Infrastructure.PostgresKitchenTicketStore;using MigrationApplication=MIGRATIONS::MigrationApplication;using Npgsql;
namespace NexaConnect.IntegrationTests;
[Collection("Kitchen migration runner acceptance")]public sealed class KitchenMigrationRunnerAcceptanceTests
{
 [KitchenMigrationFact]public async Task Empty_database_runs_0_to_3_to_2_to_3(){string admin=Environment.GetEnvironmentVariable("NEXACONNECT_POSTGRES_ADMIN_INTEGRATION_DB")!;string name=$"nexaconnect_kitchen_clean_it_{Guid.NewGuid():N}";Validate(name);var ab=new NpgsqlConnectionStringBuilder(admin){Database="postgres"};await using var ads=NpgsqlDataSource.Create(ab.ConnectionString);await Create(ads,name);string? previous=Environment.GetEnvironmentVariable("NEXACONNECT_KITCHEN_DB");try{var kb=new NpgsqlConnectionStringBuilder(admin){Database=name};Environment.SetEnvironmentVariable("NEXACONNECT_KITCHEN_DB",kb.ConnectionString);string root=Path.Combine(Root(),"src","Tools","NexaConnect.DataMigration","Scripts");Assert.Equal(0,await Run(root,2));await using var ds=NpgsqlDataSource.Create(kb.ConnectionString);Guid legacy=await Seed(ds);Assert.Equal(0,await Run(root,3));await History(ds,[1,2,3]);await Schema3(ds);await Backfill(ds,legacy);await Exercise(ds);Assert.Equal(0,await Run(root,2,true));await History(ds,[1,2]);await using(var c=await ds.OpenConnectionAsync()){Assert.Equal("outbox_messages",await Text(c,"SELECT to_regclass('public.outbox_messages')::text"));Assert.Null(await Text(c,"SELECT to_regclass('public.kitchen_audit_records')::text"));Assert.Equal(2L,await Long(c,"SELECT count(*) FROM outbox_messages"));}Assert.Equal(0,await Run(root,3));await Schema3(ds);await Exercise(ds);}finally{Environment.SetEnvironmentVariable("NEXACONNECT_KITCHEN_DB",previous);await Drop(ads,name);}}
 private static Task<int> Run(string root,int target,bool destructive=false){var args=new List<string>{"--service","Kitchen","--scripts-root",root,"--target",target.ToString(),"--application-version","0.8.0","--confirm"};if(destructive)args.AddRange(["--allow-destructive","--backup-verified"]);return MigrationApplication.RunAsync(args.ToArray());}
 private static async Task<Guid> Seed(NpgsqlDataSource ds){Guid id=Guid.NewGuid();await using var c=await ds.OpenConnectionAsync();await using var q=new NpgsqlCommand("INSERT INTO kitchen_tickets(id,restaurant_id,branch_id,order_id,preparation_station_id,ticket_number,status,queued_at_utc,created_at_utc,updated_at_utc) VALUES($1,$2,$3,$4,$5,$6,'queued',now(),now(),now())",c);q.Parameters.AddWithValue(id);q.Parameters.AddWithValue(Guid.NewGuid());q.Parameters.AddWithValue(Guid.NewGuid());q.Parameters.AddWithValue(Guid.NewGuid());q.Parameters.AddWithValue(Guid.NewGuid());q.Parameters.AddWithValue($"K-{Guid.NewGuid():N}");await q.ExecuteNonQueryAsync();return id;}
 private static async Task Backfill(NpgsqlDataSource ds,Guid id){await using var c=await ds.OpenConnectionAsync();Assert.Equal(Guid.Empty,(Guid)(await new NpgsqlCommand($"SELECT organization_id FROM kitchen_tickets WHERE id='{id:D}'",c).ExecuteScalarAsync())!);Guid org=Guid.NewGuid();await using var q=new NpgsqlCommand("UPDATE kitchen_tickets SET organization_id=$1,preparation_station_code='legacy-station',request_fingerprint=$2 WHERE id=$3",c);q.Parameters.AddWithValue(org);q.Parameters.AddWithValue(new string('A',64));q.Parameters.AddWithValue(id);await q.ExecuteNonQueryAsync();}
 private static async Task Exercise(NpgsqlDataSource ds){var repo=new KitchenRepository(ds);var ticket=await repo.CreateAsync(Guid.NewGuid(),new KitchenCreate(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),[new KitchenLine(Guid.NewGuid(),"Burger",1,"grill")]),new KitchenContext("migration-test",Guid.NewGuid()),default);await using var c=await ds.OpenConnectionAsync();Assert.Equal(1L,await Long(c,"SELECT count(*) FROM kitchen_audit_records WHERE kitchen_ticket_id=$1",ticket.TicketId));Assert.Equal(2L,await Long(c,"SELECT count(*) FROM outbox_messages WHERE aggregate_id=$1",ticket.TicketId));}
 private static async Task Schema3(NpgsqlDataSource ds){await using var c=await ds.OpenConnectionAsync();Assert.Equal("kitchen_audit_records",await Text(c,"SELECT to_regclass('public.kitchen_audit_records')::text"));Assert.Equal("organization_id",await Text(c,"SELECT column_name FROM information_schema.columns WHERE table_name='kitchen_tickets' AND column_name='organization_id'"));Assert.Equal(1L,await Long(c,"SELECT count(*) FROM pg_trigger WHERE tgname='tr_kitchen_history_append_only' AND NOT tgisinternal"));}
 private static async Task History(NpgsqlDataSource ds,int[] expected){await using var c=await ds.OpenConnectionAsync();await using var q=new NpgsqlCommand("SELECT version FROM nexaconnect_schema_migrations ORDER BY version",c);await using var r=await q.ExecuteReaderAsync();var actual=new List<int>();while(await r.ReadAsync())actual.Add(r.GetInt32(0));Assert.Equal(expected,actual);}
 private static async Task<long> Long(NpgsqlConnection c,string sql,params object[] values){await using var q=new NpgsqlCommand(sql,c);for(int i=0;i<values.Length;i++)q.Parameters.AddWithValue(values[i]);return Convert.ToInt64(await q.ExecuteScalarAsync());}private static async Task<string?> Text(NpgsqlConnection c,string sql){object? x=await new NpgsqlCommand(sql,c).ExecuteScalarAsync();return x is null or DBNull?null:Convert.ToString(x);}
 private static async Task Create(NpgsqlDataSource ds,string name){await using var c=await ds.OpenConnectionAsync();await new NpgsqlCommand($"CREATE DATABASE {new NpgsqlCommandBuilder().QuoteIdentifier(name)}",c).ExecuteNonQueryAsync();}private static async Task Drop(NpgsqlDataSource ds,string name){Validate(name);await using var c=await ds.OpenConnectionAsync();await new NpgsqlCommand($"DROP DATABASE IF EXISTS {new NpgsqlCommandBuilder().QuoteIdentifier(name)} WITH (FORCE)",c).ExecuteNonQueryAsync();}private static void Validate(string name){if(!System.Text.RegularExpressions.Regex.IsMatch(name,"^nexaconnect_kitchen_clean_it_[a-f0-9]{32}$"))throw new InvalidOperationException("Unsafe Kitchen acceptance database name.");}private static string Root(){DirectoryInfo? d=new(AppContext.BaseDirectory);while(d is not null&&!File.Exists(Path.Combine(d.FullName,"NexaConnect.sln")))d=d.Parent;return d?.FullName??throw new DirectoryNotFoundException();}
}
[CollectionDefinition("Kitchen migration runner acceptance",DisableParallelization=true)]public sealed class KitchenMigrationRunnerCollection;
public sealed class KitchenMigrationFactAttribute:FactAttribute{public KitchenMigrationFactAttribute(){string? e=Environment.GetEnvironmentVariable("NEXACONNECT_ENVIRONMENT")??Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT")??Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");if(Environment.GetEnvironmentVariable("NEXACONNECT_KITCHEN_CLEAN_INSTALL_ACCEPTANCE")!="1"||string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("NEXACONNECT_POSTGRES_ADMIN_INTEGRATION_DB"))||e is not("Development" or "Test" or "Testing"))Skip="Kitchen migration acceptance requires opt-in, admin connection, and safe environment.";}}
