extern alias KITCHEN;
using KitchenContext=KITCHEN::NexaConnect.Services.Kitchen.Application.KitchenMutationContext;using KitchenCreate=KITCHEN::NexaConnect.Services.Kitchen.Application.CreateKitchenTicket;using KitchenLine=KITCHEN::NexaConnect.Services.Kitchen.Application.KitchenTicketLine;using KitchenStatus=KITCHEN::NexaConnect.Services.Kitchen.Domain.KitchenTicketStatus;using KitchenTransition=KITCHEN::NexaConnect.Services.Kitchen.Application.TransitionKitchenTicket;using KitchenRepository=KITCHEN::NexaConnect.Services.Kitchen.Infrastructure.PostgresKitchenTicketStore;using Microsoft.Extensions.Options;using NexaConnect.Infrastructure.Messaging;using Npgsql;using RabbitMQ.Client;
namespace NexaConnect.IntegrationTests;
public sealed class KitchenPostgresIntegrationTests:IAsyncLifetime
{
 private readonly string? value=Environment.GetEnvironmentVariable("NEXACONNECT_KITCHEN_INTEGRATION_DB");private NpgsqlDataSource? dataSource;private string? schema;
 [KitchenDatabaseFact]public async Task Multi_station_idempotency_and_lifecycle_are_atomic(){Guid organization=Guid.NewGuid(),restaurant=Guid.NewGuid(),branch=Guid.NewGuid(),order=Guid.NewGuid(),correlation=Guid.NewGuid();var repo=new KitchenRepository(dataSource!);var context=new KitchenContext("kitchen-test",correlation);var grill=new KitchenCreate(restaurant,order,branch,[new KitchenLine(Guid.NewGuid(),"Burger",1,"grill")]);var bar=new KitchenCreate(restaurant,order,branch,[new KitchenLine(Guid.NewGuid(),"Cola",1,"bar")]);var first=await repo.CreateAsync(organization,grill,context,default);var replay=await repo.CreateAsync(organization,grill,context,default);var second=await repo.CreateAsync(organization,bar,context,default);Assert.Equal(first.TicketId,replay.TicketId);Assert.NotEqual(first.TicketId,second.TicketId);var started=await repo.TransitionAsync(organization,first.TicketId,new KitchenTransition(KitchenStatus.InProgress,1),context,default);var ready=await repo.TransitionAsync(organization,first.TicketId,new KitchenTransition(KitchenStatus.Ready,2),context,default);Assert.Equal(3,ready.ConcurrencyVersion);Assert.Single(ready.Lines);Assert.Null(await repo.GetAsync(Guid.NewGuid(),first.TicketId,default));await using var connection=await dataSource!.OpenConnectionAsync();Assert.Equal(4L,await Scalar(connection,"SELECT count(*) FROM kitchen_status_history"));Assert.Equal(4L,await Scalar(connection,"SELECT count(*) FROM kitchen_audit_records"));Assert.Equal(8L,await Scalar(connection,"SELECT count(*) FROM outbox_messages"));await using var mutate=new NpgsqlCommand("DELETE FROM kitchen_status_history",connection);await Assert.ThrowsAsync<PostgresException>(()=>mutate.ExecuteNonQueryAsync());}
 [KitchenDatabaseFact]public async Task Outbox_failure_rolls_back_ticket_history_and_audit(){Guid organization=Guid.NewGuid(),order=Guid.NewGuid();await using(var c=await dataSource!.OpenConnectionAsync())await new NpgsqlCommand("ALTER TABLE outbox_messages RENAME TO unavailable_outbox_messages",c).ExecuteNonQueryAsync();try{var repo=new KitchenRepository(dataSource!);await Assert.ThrowsAsync<PostgresException>(()=>repo.CreateAsync(organization,new(Guid.NewGuid(),order,Guid.NewGuid(),[new(Guid.NewGuid(),"Burger",1,"grill")]),new("kitchen-test",Guid.NewGuid()),default));}finally{await using var c=await dataSource!.OpenConnectionAsync();await new NpgsqlCommand("ALTER TABLE unavailable_outbox_messages RENAME TO outbox_messages",c).ExecuteNonQueryAsync();}await using var verify=await dataSource!.OpenConnectionAsync();Assert.Equal(0L,await Scalar(verify,"SELECT count(*) FROM kitchen_tickets WHERE organization_id=$1 AND order_id=$2",organization,order));Assert.Equal(0L,await Scalar(verify,"SELECT count(*) FROM kitchen_audit_records WHERE organization_id=$1",organization));}
 [KitchenRabbitFact]public async Task Broker_recovery_publishes_confirmed_lifecycle_messages(){string uri=Environment.GetEnvironmentVariable("NEXACONNECT_RABBITMQ_INTEGRATION_URI")!;await Assert.ThrowsAnyAsync<Exception>(async()=>{var f=new ConnectionFactory{Uri=new Uri("amqp://guest:guest@127.0.0.1:1"),RequestedConnectionTimeout=TimeSpan.FromSeconds(1)};await using var ignored=await f.CreateConnectionAsync();});Guid organization=Guid.NewGuid(),correlation=Guid.NewGuid();var repo=new KitchenRepository(dataSource!);var context=new KitchenContext("kitchen-recovery",correlation);var ticket=await repo.CreateAsync(organization,new(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),[new(Guid.NewGuid(),"Burger",1,"grill")]),context,default);await repo.TransitionAsync(organization,ticket.TicketId,new KitchenTransition(KitchenStatus.InProgress,1),context,default);string exchange=$"nexaconnect.kitchen.phase11.{Guid.NewGuid():N}",queue=$"nexaconnect.kitchen.phase11.{Guid.NewGuid():N}";await using var connection=await new ConnectionFactory{Uri=new Uri(uri)}.CreateConnectionAsync();await using var channel=await connection.CreateChannelAsync();try{await channel.ExchangeDeclareAsync(exchange,ExchangeType.Topic,true,false);await channel.QueueDeclareAsync(queue,false,true,true);await channel.QueueBindAsync(queue,exchange,"kitchen.#");var transport=new RabbitMqOutboxTransport(connection,Options.Create(new OutboxOptions{Exchange=exchange}));var store=new PostgresOutboxStore(dataSource!);var pending=(await store.ClaimBatchAsync(10,default)).Where(x=>x.AggregateId==ticket.TicketId).ToArray();Assert.Equal(4,pending.Length);foreach(var message in pending){await transport.PublishAsync(message,default);await store.MarkPublishedAsync(message.Id,default);}var deliveries=new List<BasicGetResult>();for(int i=0;i<30&&deliveries.Count<4;i++){var item=await channel.BasicGetAsync(queue,true);if(item is null)await Task.Delay(100);else deliveries.Add(item);}Assert.Equal(["kitchen.audit.v1","kitchen.audit.v1","kitchen.ticket-queued.v1","kitchen.ticket-status-changed.v1"],deliveries.Select(x=>x.RoutingKey).Order().ToArray());Assert.All(deliveries,x=>Assert.True(x.BasicProperties.Persistent));}finally{await channel.ExchangeDeleteAsync(exchange,false);}}
 public async Task InitializeAsync(){if(string.IsNullOrWhiteSpace(value)||!Safe())return;schema=$"kitchen_phase10_it_{Guid.NewGuid():N}";var b=new NpgsqlConnectionStringBuilder(value){SearchPath=schema};dataSource=NpgsqlDataSource.Create(b.ConnectionString);await using var c=await dataSource.OpenConnectionAsync();await new NpgsqlCommand($"CREATE SCHEMA \"{schema}\"",c).ExecuteNonQueryAsync();await new NpgsqlCommand(Schema,c).ExecuteNonQueryAsync();}
 public async Task DisposeAsync(){if(dataSource is null||schema is null)return;await using var c=await dataSource.OpenConnectionAsync();await new NpgsqlCommand($"DROP SCHEMA IF EXISTS \"{schema}\" CASCADE",c).ExecuteNonQueryAsync();await dataSource.DisposeAsync();}
 private static async Task<long> Scalar(NpgsqlConnection c,string sql,params object[] values){await using var q=new NpgsqlCommand(sql,c);for(int i=0;i<values.Length;i++)q.Parameters.AddWithValue(values[i]);return(long)(await q.ExecuteScalarAsync()??0L);}private static bool Safe(){string? e=Environment.GetEnvironmentVariable("NEXACONNECT_ENVIRONMENT")??Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT")??Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");return e is "Development" or "Test" or "Testing";}
 private const string Schema="""
 CREATE TABLE kitchen_tickets(id uuid PRIMARY KEY,organization_id uuid NOT NULL,restaurant_id uuid NOT NULL,branch_id uuid NOT NULL,order_id uuid NOT NULL,preparation_station_id uuid NOT NULL,preparation_station_code text NOT NULL,ticket_number text NOT NULL,request_fingerprint text NOT NULL,service_sequence integer NOT NULL DEFAULT 1,priority integer NOT NULL DEFAULT 0,status text NOT NULL,queued_at_utc timestamptz NOT NULL,started_at_utc timestamptz NULL,ready_at_utc timestamptz NULL,completed_at_utc timestamptz NULL,cancelled_at_utc timestamptz NULL,created_at_utc timestamptz NOT NULL,updated_at_utc timestamptz NOT NULL,concurrency_version bigint NOT NULL DEFAULT 1,UNIQUE(organization_id,restaurant_id,branch_id,ticket_number),UNIQUE(organization_id,order_id,preparation_station_id,service_sequence));
 CREATE TABLE kitchen_ticket_items(id uuid PRIMARY KEY,kitchen_ticket_id uuid NOT NULL REFERENCES kitchen_tickets(id),order_line_id uuid NOT NULL,product_id uuid NOT NULL,item_name_snapshot text NOT NULL,quantity numeric(12,3) NOT NULL,status text NOT NULL,queued_at_utc timestamptz NOT NULL,started_at_utc timestamptz NULL,ready_at_utc timestamptz NULL,completed_at_utc timestamptz NULL,cancelled_at_utc timestamptz NULL,updated_at_utc timestamptz NOT NULL,concurrency_version bigint NOT NULL DEFAULT 1,UNIQUE(kitchen_ticket_id,order_line_id));
 CREATE TABLE kitchen_status_history(id uuid PRIMARY KEY,kitchen_ticket_id uuid NOT NULL REFERENCES kitchen_tickets(id),kitchen_ticket_item_id uuid NULL,entity_type text NOT NULL,from_status text NULL,to_status text NOT NULL,reason_code text NULL,changed_at_utc timestamptz NOT NULL,changed_by text NOT NULL);
 CREATE TABLE kitchen_audit_records(id uuid PRIMARY KEY,organization_id uuid NOT NULL,restaurant_id uuid NOT NULL,branch_id uuid NOT NULL,order_id uuid NOT NULL,kitchen_ticket_id uuid NOT NULL REFERENCES kitchen_tickets(id),action text NOT NULL,actor_subject_id text NOT NULL,occurred_at_utc timestamptz NOT NULL);
 CREATE FUNCTION prevent_kitchen_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'append-only'; END; $$;CREATE TRIGGER tr_kitchen_audit_append_only BEFORE UPDATE OR DELETE ON kitchen_audit_records FOR EACH ROW EXECUTE FUNCTION prevent_kitchen_audit_mutation();CREATE TRIGGER tr_kitchen_history_append_only BEFORE UPDATE OR DELETE ON kitchen_status_history FOR EACH ROW EXECUTE FUNCTION prevent_kitchen_audit_mutation();
 CREATE TABLE outbox_messages(id uuid PRIMARY KEY,event_type text NOT NULL,contract_version integer NOT NULL,aggregate_type text NOT NULL,aggregate_id uuid NOT NULL,payload jsonb NOT NULL,correlation_id text NULL,causation_id text NULL,occurred_at_utc timestamptz NOT NULL,published_at_utc timestamptz NULL,retry_count integer NOT NULL DEFAULT 0,next_attempt_at_utc timestamptz NULL,last_error_category text NULL);
 """;
}
public class KitchenDatabaseFactAttribute:FactAttribute{public KitchenDatabaseFactAttribute(){string? e=Environment.GetEnvironmentVariable("NEXACONNECT_ENVIRONMENT")??Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT")??Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");if(string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("NEXACONNECT_KITCHEN_INTEGRATION_DB"))||e is not("Development" or "Test" or "Testing"))Skip="Kitchen PostgreSQL acceptance requires its connection and safe environment.";}}
public sealed class KitchenRabbitFactAttribute:KitchenDatabaseFactAttribute{public KitchenRabbitFactAttribute(){if(Environment.GetEnvironmentVariable("NEXACONNECT_RABBITMQ_ACCEPTANCE")!="1"||!Uri.TryCreate(Environment.GetEnvironmentVariable("NEXACONNECT_RABBITMQ_INTEGRATION_URI"),UriKind.Absolute,out _))Skip="Kitchen RabbitMQ acceptance requires its opt-in and URI.";}}
