<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\NexaConnect.Infrastructure\NexaConnect.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\NexaConnect.Observability\NexaConnect.Observability.csproj" />
    <ProjectReference Include="..\..\..\src\Gateway\NexaConnect.Gateway\NexaConnect.Gateway.csproj" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.POS\NexaConnect.Services.POS.csproj" Aliases="POS" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Authorization\NexaConnect.Services.Authorization.csproj" Aliases="AUTH" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Catalog\NexaConnect.Services.Catalog.csproj" Aliases="CATALOG" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Inventory\NexaConnect.Services.Inventory.csproj" Aliases="INVENTORY" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Order\NexaConnect.Services.Order.csproj" Aliases="ORDER" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Payment\NexaConnect.Services.Payment.csproj" Aliases="PAYMENT" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Kitchen\NexaConnect.Services.Kitchen.csproj" Aliases="KITCHEN" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.PlatformDirectory\NexaConnect.Services.PlatformDirectory.csproj" Aliases="DIRECTORY" />
    <ProjectReference Include="..\..\..\src\Gateway\NexaConnect.PlatformAdminBff\NexaConnect.PlatformAdminBff.csproj" Aliases="PLATFORMADMIN" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
