using Amazon.S3;using Amazon.S3.Model;using NexaConnect.Services.Media.Application;
namespace NexaConnect.Services.Media.Infrastructure;
public sealed class MediaStorageOptions{public string Bucket{get;set;}="";}
public sealed class S3MediaObjectStorage(IAmazonS3 s3,IConfiguration configuration):IMediaObjectStorage
{
 readonly string bucket=configuration["MediaStorage:Bucket"]??throw new InvalidOperationException("MediaStorage:Bucket is required.");
 readonly Protocol protocol=new Uri(configuration["MediaStorage:ServiceUrl"]??throw new InvalidOperationException("MediaStorage:ServiceUrl is required.")).Scheme==Uri.UriSchemeHttps?Protocol.HTTPS:Protocol.HTTP;
 public Task<string>CreateUploadUrlAsync(string key,string type,long size,string checksum,TimeSpan life,CancellationToken c){var request=new GetPreSignedUrlRequest{BucketName=bucket,Key=key,Verb=HttpVerb.PUT,ContentType=type,Expires=DateTime.UtcNow.Add(life),Protocol=protocol};request.Headers["x-amz-checksum-sha256"]=Convert.ToBase64String(Convert.FromHexString(checksum));return s3.GetPreSignedURLAsync(request);}
 public Task<string>CreateDownloadUrlAsync(string key,TimeSpan life,CancellationToken c)=>s3.GetPreSignedURLAsync(new GetPreSignedUrlRequest{BucketName=bucket,Key=key,Verb=HttpVerb.GET,Expires=DateTime.UtcNow.Add(life),Protocol=protocol});
 public async Task<StoredObjectInfo?>InspectAsync(string key,CancellationToken c){try{var value=await s3.GetObjectMetadataAsync(new GetObjectMetadataRequest{BucketName=bucket,Key=key,ChecksumMode=ChecksumMode.ENABLED},c);string? hash=string.IsNullOrWhiteSpace(value.ChecksumSHA256)?null:Convert.ToHexString(Convert.FromBase64String(value.ChecksumSHA256)).ToLowerInvariant();return new(value.ContentLength,hash);}catch(AmazonS3Exception e)when(e.StatusCode==System.Net.HttpStatusCode.NotFound){return null;}}
 public async Task<byte[]>ReadAsync(string key,long maximumBytes,CancellationToken c){if(maximumBytes is <1 or >10_485_760)throw new ArgumentOutOfRangeException(nameof(maximumBytes));using GetObjectResponse response=await s3.GetObjectAsync(new GetObjectRequest{BucketName=bucket,Key=key,ChecksumMode=ChecksumMode.ENABLED},c);if(response.ContentLength>maximumBytes)throw new InvalidOperationException("Stored object exceeds its declared size.");using var output=new MemoryStream(response.ContentLength is >0 and <=10_485_760?(int)response.ContentLength:0);byte[] buffer=new byte[81920];while(true){int allowed=(int)Math.Min(buffer.Length,maximumBytes-output.Length+1);int read=await response.ResponseStream.ReadAsync(buffer.AsMemory(0,allowed),c);if(read==0)break;await output.WriteAsync(buffer.AsMemory(0,read),c);if(output.Length>maximumBytes)throw new InvalidOperationException("Stored object exceeds its declared size.");}return output.ToArray();}
 public Task DeleteAsync(string key,CancellationToken c)=>s3.DeleteObjectAsync(new DeleteObjectRequest{BucketName=bucket,Key=key},c);
}
