@NexaConnect.Services.Inventory_HostAddress = http://localhost:5220

GET {{NexaConnect.Services.Inventory_HostAddress}}/api/inventory/v1/branches/00000000-0000-0000-0000-000000000001/stock
Accept: application/json

###
