using NexaConnect.Services.Restaurant.Application.Branches;using Npgsql;
namespace NexaConnect.Services.Restaurant.Infrastructure.Persistence;
public sealed class PostgresBranchManagementRepository(NpgsqlDataSource dataSource):IBranchManagementRepository
{
 public async Task<IReadOnlyCollection<BranchSummary>> ListAsync(Guid organizationId,CancellationToken c){const string sql="SELECT b.id,b.restaurant_id,r.organization_id,b.code,b.name,b.time_zone,b.currency,b.status,b.opened_at_utc,b.closed_at_utc,b.concurrency_version FROM branches b JOIN restaurants r ON r.id=b.restaurant_id WHERE r.organization_id=$1 AND r.status='active' ORDER BY b.name,b.id;";await using var cn=await dataSource.OpenConnectionAsync(c);await using var cmd=new NpgsqlCommand(sql,cn);cmd.Parameters.AddWithValue(organizationId);var rows=new List<BranchSummary>();await using var reader=await cmd.ExecuteReaderAsync(c);while(await reader.ReadAsync(c))rows.Add(Read(reader));return rows;}
 public async Task<BranchSummary?> CreateAsync(Guid organizationId,CreateManagedBranchCommand command,string actor,CancellationToken c){await using var cn=await dataSource.OpenConnectionAsync(c);await using var tx=await cn.BeginTransactionAsync(c);const string sql="INSERT INTO branches(id,restaurant_id,code,name,time_zone,currency,status,opened_at_utc,created_at_utc,created_by,updated_at_utc,updated_by) SELECT $1,r.id,$2,$3,$4,$5,'active',now(),now(),$6,now(),$6 FROM restaurants r WHERE r.id=$7 AND r.organization_id=$8 AND r.status='active' RETURNING id,restaurant_id,(SELECT organization_id FROM restaurants WHERE id=$7),code,name,time_zone,currency,status,opened_at_utc,closed_at_utc,concurrency_version;";await using var cmd=new NpgsqlCommand(sql,cn,tx);cmd.Parameters.AddWithValue(Guid.NewGuid());cmd.Parameters.AddWithValue(command.Code);cmd.Parameters.AddWithValue(command.Name);cmd.Parameters.AddWithValue(command.TimeZone);cmd.Parameters.AddWithValue(command.Currency);cmd.Parameters.AddWithValue(actor);cmd.Parameters.AddWithValue(command.RestaurantId);cmd.Parameters.AddWithValue(organizationId);BranchSummary? result;try{await using var reader=await cmd.ExecuteReaderAsync(c);result=await reader.ReadAsync(c)?Read(reader):null;}catch(PostgresException e)when(e.SqlState==PostgresErrorCodes.UniqueViolation){throw new BranchConflictException("Branch code already exists.");}if(result is null){await tx.RollbackAsync(c);return null;}await Audit(cn,tx,"branch.created",result,actor,c);await tx.CommitAsync(c);return result;}
 public async Task<BranchSummary?> UpdateAsync(Guid organizationId,Guid branchId,UpdateManagedBranchCommand command,string actor,CancellationToken c){await using var cn=await dataSource.OpenConnectionAsync(c);await using var tx=await cn.BeginTransactionAsync(c);const string sql="UPDATE branches b SET name=$3,time_zone=$4,currency=$5,status=$6,closed_at_utc=CASE WHEN $6='closed' THEN COALESCE(closed_at_utc,now()) ELSE NULL END,updated_at_utc=now(),updated_by=$7,concurrency_version=concurrency_version+1 FROM restaurants r WHERE b.restaurant_id=r.id AND r.organization_id=$1 AND b.id=$2 AND b.concurrency_version=$8 RETURNING b.id,b.restaurant_id,r.organization_id,b.code,b.name,b.time_zone,b.currency,b.status,b.opened_at_utc,b.closed_at_utc,b.concurrency_version;";await using var cmd=new NpgsqlCommand(sql,cn,tx);cmd.Parameters.AddWithValue(organizationId);cmd.Parameters.AddWithValue(branchId);cmd.Parameters.AddWithValue(command.Name);cmd.Parameters.AddWithValue(command.TimeZone);cmd.Parameters.AddWithValue(command.Currency);cmd.Parameters.AddWithValue(command.Status);cmd.Parameters.AddWithValue(actor);cmd.Parameters.AddWithValue(command.ExpectedVersion);await using var reader=await cmd.ExecuteReaderAsync(c);BranchSummary? result=await reader.ReadAsync(c)?Read(reader):null;if(result is null){await tx.RollbackAsync(c);throw new BranchConflictException("Branch was not found in the organization or changed concurrently.");}await reader.DisposeAsync();await Audit(cn,tx,"branch.updated",result,actor,c);await tx.CommitAsync(c);return result;}
 private static async Task Audit(NpgsqlConnection cn,NpgsqlTransaction tx,string action,BranchSummary result,string actor,CancellationToken c){await using var cmd=new NpgsqlCommand("INSERT INTO branch_management_audit(id,organization_id,branch_id,action,actor_subject_id,occurred_at_utc) VALUES($1,$2,$3,$4,$5,now());",cn,tx);cmd.Parameters.AddWithValue(Guid.NewGuid());cmd.Parameters.AddWithValue(result.OrganizationId);cmd.Parameters.AddWithValue(result.BranchId);cmd.Parameters.AddWithValue(action);cmd.Parameters.AddWithValue(actor);await cmd.ExecuteNonQueryAsync(c);}
 private static BranchSummary Read(NpgsqlDataReader r)=>new(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.IsDBNull(8)?null:r.GetFieldValue<DateTimeOffset>(8),r.IsDBNull(9)?null:r.GetFieldValue<DateTimeOffset>(9),r.GetInt64(10));
}
