using NexaConnect.Contracts.IntegrationEvents;using NexaConnect.Services.Reporting.Application;using NexaConnect.Services.Reporting.Infrastructure.Messaging;
namespace NexaConnect.UnitTests;
public sealed class ActivityServiceTests
{
 [Fact]public async Task Query_round_trips_opaque_cursor_and_normalizes_application(){var repo=new Repo();var service=new ActivityService(repo);Guid id=Guid.NewGuid();DateTimeOffset time=DateTimeOffset.UtcNow;await service.QueryAsync(Guid.NewGuid()," NEXA_CONNECT "," actor ",null,ActivityService.Encode(time,id),50,default);Assert.Equal(id,repo.Filter!.BeforeEventId);Assert.Equal(time,repo.Filter.BeforeUtc);Assert.Equal("nexa_connect",repo.Filter.ApplicationCode);Assert.Equal("actor",repo.Filter.ActorSubjectId);}
 [Fact]public async Task Query_rejects_invalid_cursor_and_limit(){var service=new ActivityService(new Repo());await Assert.ThrowsAsync<ArgumentException>(()=>service.QueryAsync(Guid.NewGuid(),"nexa_connect",null,null,"bad",50,default));await Assert.ThrowsAsync<ArgumentException>(()=>service.QueryAsync(Guid.NewGuid(),"nexa_connect",null,null,null,201,default));}
 [Fact]public async Task Projection_requires_tenant_and_safe_fields(){var service=new ActivityService(new Repo());var invalid=new PlatformAuditEventV1(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,"actor",null,"action","type","id","succeeded");await Assert.ThrowsAsync<ArgumentException>(()=>service.ProjectAsync(new(invalid,"nexa_connect","restaurant"),default));}
 [Fact]public async Task Projection_rejects_unknown_or_control_text(){var service=new ActivityService(new Repo());var value=new PlatformAuditEventV1(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,"actor",Guid.NewGuid(),"free.text","branch","id","succeeded");await Assert.ThrowsAsync<ArgumentException>(()=>service.ProjectAsync(new(value,"nexa_connect","restaurant"),default));value=value with{Action="branch.updated",SubjectId="actor\nspoof"};await Assert.ThrowsAsync<ArgumentException>(()=>service.ProjectAsync(new(value,"nexa_connect","restaurant"),default));}
 [Fact]public async Task Projection_accepts_bounded_restaurant_event(){var service=new ActivityService(new Repo());var value=new PlatformAuditEventV1(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,"actor",Guid.NewGuid(),"branch.updated","branch",Guid.NewGuid().ToString("D"),"succeeded");Assert.True(await service.ProjectAsync(new(value,"nexa_connect","restaurant"),default));}
 [Fact]public async Task Projection_accepts_payment_intent_audit(){var service=new ActivityService(new Repo());var value=new PlatformAuditEventV1(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,"actor",Guid.NewGuid(),"payment.intent.created","payment-intent",Guid.NewGuid().ToString("D"),"succeeded");Assert.True(await service.ProjectAsync(new(value,"nexa_connect","payment"),default));}
 [Fact]public async Task Projection_accepts_order_payment_review_audit(){var service=new ActivityService(new Repo());var value=new PlatformAuditEventV1(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,"actor",Guid.NewGuid(),"order.payment-review.resolved","order",Guid.NewGuid().ToString("D"),"succeeded");Assert.True(await service.ProjectAsync(new(value,"nexa_connect","order"),default));}
 [Fact]public void Order_audit_routing_resolves_to_order_source(){Assert.Equal("order",ActivityAuditRouting.ResolveSource("order.audit.v1"));}
 [Theory][InlineData("payment.authorization.started")][InlineData("payment.authorization.succeeded")][InlineData("payment.authorization.failed")]public async Task Projection_accepts_payment_authorization_audit(string action){var service=new ActivityService(new Repo());var value=new PlatformAuditEventV1(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,"actor",Guid.NewGuid(),action,"payment-intent",Guid.NewGuid().ToString("D"),"succeeded");Assert.True(await service.ProjectAsync(new(value,"nexa_connect","payment"),default));}
 [Fact]public async Task Projection_accepts_kitchen_ticket_audit(){var service=new ActivityService(new Repo());var value=new PlatformAuditEventV1(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,"actor",Guid.NewGuid(),"kitchen.ticket.ready","kitchen-ticket",Guid.NewGuid().ToString("D"),"succeeded");Assert.True(await service.ProjectAsync(new(value,"nexa_connect","kitchen"),default));}
 [Fact]public async Task Projection_accepts_customer_profile_audit(){var service=new ActivityService(new Repo());var value=new PlatformAuditEventV1(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,"actor",Guid.NewGuid(),"customer.profile.created","customer-profile",Guid.NewGuid().ToString("D"),"succeeded");Assert.True(await service.ProjectAsync(new(value,"nexa_connect","customer"),default));}
 private sealed class Repo:IActivityProjectionRepository{public ActivityFilter? Filter;public Task<ActivityPage> QueryAsync(ActivityFilter filter,CancellationToken c){Filter=filter;return Task.FromResult(new ActivityPage([],null));}public Task<bool> ProjectAsync(ProjectAuditActivityCommand command,CancellationToken c)=>Task.FromResult(true);}
}
