using System.Security.Claims;using Microsoft.AspNetCore.Http;using Microsoft.AspNetCore.Mvc;using NexaConnect.Contracts.Platform;using NexaConnect.Services.Kitchen.Application;using NexaConnect.Services.Kitchen.Application.Tenant;using NexaConnect.Services.Kitchen.Controllers;using NexaConnect.Services.Kitchen.Domain;
namespace NexaConnect.UnitTests;
public sealed class KitchenWorkloadAuthorizationTests
{
 [Fact]public async Task Only_order_workload_with_organization_can_create(){var store=new Store();var denied=Controller(store,"nexaconnect-catalog-service",true);Assert.IsType<ForbidResult>((await denied.Create(Command(),default)).Result);var missing=Controller(store,"nexaconnect-order-service",false);Assert.IsType<BadRequestObjectResult>((await missing.Create(Command(),default)).Result);var allowed=Controller(store,"nexaconnect-order-service",true);Assert.IsType<CreatedAtActionResult>((await allowed.Create(Command(),default)).Result);Assert.Equal(1,store.Count);}
 private static KitchenTicketsController Controller(Store store,string azp,bool organization){var http=new DefaultHttpContext{User=new ClaimsPrincipal(new ClaimsIdentity([new Claim("azp",azp)],"test"))};if(organization)http.Request.Headers[TenantContextHeaders.OrganizationId]=Guid.NewGuid().ToString("D");return new(store,new Deny()){ControllerContext=new ControllerContext{HttpContext=http}};}
 private static CreateKitchenTicket Command()=>new(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),[new(Guid.NewGuid(),"Burger",1,"grill")]);
 private sealed class Deny:IKitchenTenantAuthorizer{public Task<bool> HasBranchAccessAsync(Guid organizationId,Guid branchId,string permission,string authorizationHeader,CancellationToken token)=>Task.FromResult(false);}
 private sealed class Store:IKitchenTicketStore{public int Count;public Task<KitchenTicket> CreateAsync(Guid organizationId,CreateKitchenTicket c,KitchenMutationContext x,CancellationToken token){Count++;return Task.FromResult(new KitchenTicket(Guid.NewGuid(),organizationId,c.RestaurantId,c.OrderId,c.BranchId,Guid.NewGuid(),KitchenTicketStatus.Queued,1,DateTimeOffset.UtcNow,c.Lines));}public Task<KitchenTicket?> GetAsync(Guid o,Guid id,CancellationToken t)=>Task.FromResult<KitchenTicket?>(null);public Task<KitchenTicket> TransitionAsync(Guid o,Guid id,TransitionKitchenTicket c,KitchenMutationContext x,CancellationToken t)=>throw new NotImplementedException();public Task<bool> CancelAsync(Guid o,Guid b,Guid id,KitchenMutationContext x,CancellationToken t)=>Task.FromResult(false);}
}
