using NexaConnect.Services.Media.Application;
namespace NexaConnect.UnitTests;
public sealed class MediaManagementTests
{
 [Fact]public async Task Start_rejects_unsafe_type_size_and_owner(){var service=new MediaManagement(new Repo(),new Storage());await Assert.ThrowsAsync<ArgumentException>(()=>service.StartAsync(Guid.NewGuid(),new("other","product",Guid.NewGuid(),"a.exe","application/octet-stream",1,new string('a',64)),"actor",default));await Assert.ThrowsAsync<ArgumentException>(()=>service.StartAsync(Guid.NewGuid(),new("catalog","product",Guid.NewGuid(),"a.png","image/png",10_485_761,new string('a',64)),"actor",default));}
 [Fact]public async Task Start_generates_tenant_scoped_key_and_normalizes(){var repo=new Repo();var service=new MediaManagement(repo,new Storage());Guid org=Guid.NewGuid();await service.StartAsync(org,new(" CATALOG "," PRODUCT ",Guid.NewGuid(),"../image.png","IMAGE/PNG",12,new string('a',64))," actor ",default);Assert.StartsWith($"organizations/{org:D}/assets/",repo.Key);Assert.Equal("image.png",repo.Command!.FileName);}
 [Fact]public async Task Complete_requires_size_and_checksum_match(){var repo=new Repo{Found=Asset()};var storage=new Storage{Info=new(9,new string('b',64))};var service=new MediaManagement(repo,storage);await Assert.ThrowsAsync<InvalidOperationException>(()=>service.CompleteAsync(repo.Org,repo.Id,1,"actor",default));}
 static (MediaAssetSummary Asset,string Key,string Checksum)Asset(){Guid id=Guid.NewGuid();return(new(id,"catalog","product",Guid.NewGuid(),"a.png","image/png",10,"pending",DateTimeOffset.UtcNow,null,1),"key",new string('a',64));}
 sealed class Storage:IMediaObjectStorage{public StoredObjectInfo?Info;public Task<string>CreateUploadUrlAsync(string k,string t,long s,string h,TimeSpan l,CancellationToken c)=>Task.FromResult("https://upload.test");public Task<string>CreateDownloadUrlAsync(string k,TimeSpan l,CancellationToken c)=>Task.FromResult("https://download.test");public Task<StoredObjectInfo?>InspectAsync(string k,CancellationToken c)=>Task.FromResult(Info);public Task DeleteAsync(string k,CancellationToken c)=>Task.CompletedTask;}
 sealed class Repo:IMediaManagementRepository{public Guid Org=Guid.NewGuid(),Id=Guid.NewGuid();public string?Key;public StartMediaUploadCommand?Command;public (MediaAssetSummary Asset,string Key,string Checksum)?Found;public Task<MediaAssetSummary>StartAsync(Guid o,Guid id,string k,StartMediaUploadCommand x,string a,DateTimeOffset e,CancellationToken c){Key=k;Command=x;return Task.FromResult(new MediaAssetSummary(id,x.OwnerService,x.OwnerType,x.OwnerId,x.FileName,x.ContentType,x.SizeBytes,"pending",DateTimeOffset.UtcNow,null,1));}public Task<(MediaAssetSummary Asset,string Key,string Checksum)?>FindAsync(Guid o,Guid id,CancellationToken c)=>Task.FromResult(Found);public Task<MediaAssetSummary?>CompleteAsync(Guid o,Guid id,long v,string a,CancellationToken c)=>Task.FromResult<MediaAssetSummary?>(Found?.Asset);public Task<MediaAssetSummary?>DeleteAsync(Guid o,Guid id,long v,string a,CancellationToken c)=>Task.FromResult<MediaAssetSummary?>(Found?.Asset);}
}
