<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\NexaConnect.Infrastructure\NexaConnect.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.POS\NexaConnect.Services.POS.csproj" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Order\NexaConnect.Services.Order.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\NexaConnect.Contracts\NexaConnect.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Catalog\NexaConnect.Services.Catalog.csproj" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Inventory\NexaConnect.Services.Inventory.csproj" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Payment\NexaConnect.Services.Payment.csproj" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Customer\NexaConnect.Services.Customer.csproj" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.Notification\NexaConnect.Services.Notification.csproj" />
    <ProjectReference Include="..\..\..\src\Services\NexaConnect.Services.PlatformDirectory\NexaConnect.Services.PlatformDirectory.csproj" />
    <ProjectReference Include="..\..\..\src\Gateway\NexaConnect.CustomerBff\NexaConnect.CustomerBff.csproj" />
    <ProjectReference Include="..\..\..\src\Gateway\NexaConnect.PlatformAdminBff\NexaConnect.PlatformAdminBff.csproj" />
    <ProjectReference Include="..\..\..\src\Tools\NexaConnect.DataGeneration\NexaConnect.DataGeneration.csproj" />
    <ProjectReference Include="..\..\..\src\Tools\NexaConnect.DataMigration\NexaConnect.DataMigration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\src\Tools\NexaConnect.DataGeneration\ImportPackages\**\*"
             Link="ImportPackages\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
